In [ ]:
import numpy as np
%pylab

# Number 1

Female = 1, Male = 0.

P(X= 1,|W1=w1,...Wn = wn) >= P(X=0|...)

P(X=1 | L=l,W=w,S=s) >= P(X=0|.....)

# Reading Data
data = array containing data
X = gender, 1 = Female 0 = Male
W = weight in kgs
L = length (Height) in cms
S = shoe size (European)


In [7]:
data = np.genfromtxt(fname='biometrie2014.csv', skip_header=5, delimiter=",",converters={0: lambda x : float(x[0] == 70)})

In [9]:
print(data) #let's see if the csv file got picked up...

[[   0.    60.   183.    42. ]
 [   0.   130.   185.    45. ]
 [   0.    84.   180.    42. ]
 [   0.    65.   195.    45. ]
 [   0.    55.   170.    42. ]
 [   1.    63.   173.    41. ]
 [   0.    74.   185.    43. ]
 [   1.    50.   170.    38. ]
 [   1.    82.   180.    42. ]
 [   0.    77.   190.    44. ]
 [   0.    76.   179.    43. ]
 [   0.    66.   178.    42. ]
 [   0.    79.   186.    45. ]
 [   0.    76.   189.    44. ]
 [   0.    75.   175.    42. ]
 [   0.    90.   190.    46. ]
 [   0.    70.   180.    41. ]
 [   1.    46.   164.    36. ]
 [   0.    98.   189.    44. ]
 [   0.    79.   180.    43. ]
 [   0.    67.   189.    44. ]
 [   0.    81.   190.    45.3]
 [   0.    85.   190.    44.5]
 [   0.    75.   188.    44. ]
 [   0.    70.   178.    43. ]
 [   0.    60.   180.    43. ]
 [   0.    73.   192.    44. ]
 [   0.    76.   174.    42. ]
 [   0.    78.   187.    44. ]
 [   1.    75.   162.    38. ]
 [   1.    50.   165.    37. ]
 [   0.    76.   188.    44.5]
 [   0. 

In [ ]:
male = data[data[:,0] == 0]
female = data[data[:,0] == 1]

# Number 2
# Parameter Estimates

In [ ]:
w0avg = np.mean(male[:,1])
w1avg = np.mean(female[:,1])
print(w0avg)
print(w1avg)
l0avg = np.mean(male[:,2])
l1avg = np.mean(female[:,2])
print(l0avg)
print(l1avg)
s0avg = np.mean(male[:,3])
s1avg = np.mean(female[:,3])
print(s0avg)
print(s1avg)

In [24]:
w0std = np.std(male[:,1])
w1std = np.std(female[:,1])
print(w0std)
print(w1std)
l0std = np.std(male[:,2])
l1std = np.std(female[:,2])
print(l0std)
print(l1std)
s0std = np.std(male[:,3])
s1std = np.std(female[:,3])
print(s0std)
print(s1std)

13.7847453509
13.5892114071
6.10358683815
6.16441400297
1.23586105114
2.13437474581


# PDFs

In [25]:
import scipy.stats as sp

f_w0 = sp.norm(w0avg,w0std)
f_w1 = sp.norm(w1avg,w1std)
f_l0 = sp.norm(l0avg,l0std)
f_l1 = sp.norm(l1avg,l1std)
f_s0 = sp.norm(s0avg,s0std)
f_s1 = sp.norm(s1avg,s1std)


# Plots

# Number 3

In [26]:
def naivebayes(w,l,s):
    w0 = f_w0.pdf(w)
    w1 = f_w1.pdf(w)
    
    l0 = f_l0.pdf(l)
    l1 = f_l1.pdf(l)
    
    s0 = f_s0.pdf(s)
    s1 = f_s1.pdf(s)
    
    b = np.log(w0) + np.log(l0) + np.log(s0)
    g = np.log(w1) + np.log(l1) + np.log(s1)
    
    if(g>=b):
        return 'Female'
    else:
        return 'Male'
    

In [30]:
naivebayes(67,175,42)

'Male'